import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className="bg-white text-gray-900">
        <header className="flex items-center px-6 py-4 shadow-md bg-gradient-to-r from-purple-500 to-yellow-500 text-white">
          {/* Logo Placeholder */}
          <div className="w-15 h-15 bg-white rounded-full flex items-center justify-center">
            <img src="/logo.png" alt="logo"></img>
          </div>

          {/* Beautiful Title */}
          <h1 className="text-3xl font-extrabold tracking-wide drop-shadow-md">
            &nbsp;Saathi Mangram
          </h1>

          {/* Spacer to balance flex layout */}
          <div className="w-12 h-12" />
        </header>
        {children}
      </body>
    </html>
  );
}
